name: piDisplay
main: piDisplay.Main
version: 0.61
author: EmbeddedPi
description: This plugin ouptputs server events to an external HD44780 based LCD display.
commands:
   initialise:
      description: Runs initialise routine.
      usage: /initialise
      permission: op
      permission-message: Nope, op only!
   backlight:
      description: Switches backlight on/off.
      usage: /backlight [on/off]
      permission: op
      permission-message: As if, op only!
   display:
      description: Switches display on/off.
      usage: /display [on/off]
      permission: op
      permission-message: jog on sunshine!
   powerLED:
      description: Switches powerLED on/off.
      usage: /powerLED [on/off]
      permission: op
      permission-message: Nae chance, op only!
   displaySend:
      description: Switches powerLED on/off.
      usage: /displaySend [message]
      permission: op
      permission-message: Oh no you don't!
      
